### ISSUE TITLE
'java.lang.IllegalArgumentException: Invalid DSN: No public key provided.'

### ISSUE THREAD

**Issue by karlca** [danielmonettelli/netmaui-mitawi-app-challenge#10]
![image](https://user-images.githubusercontent.com/37470902/188368863-9d15db8d-1457-43be-a76e-ef126ee2115e.png)

**Comment by danielmonettelli** [comment]
Hi @karlca, thank you very much for reporting your issue, this error may be due to the fact that you did not add the OpenWeather API Key, the project's readme file contains the steps to generate it, I hope this solves it.

https://github.com/danimonettelli/netmaui-mitawi-app-challenge#steps-to-generate-your-api-key-in-openweather

**Comment by karlca** [comment]
I have added the OpenWeather API key，like this...
![image](https://user-images.githubusercontent.com/37470902/188446997-d5ea5671-f82f-4deb-b61c-3331eaf6258f.png)

**Comment by danielmonettelli** [comment]
Great @karlca, in case you keep getting this error, make sure your device has internet, and your location permissions are turned on.

<body>
    <div style="width:800px; margin:0 auto;">
      <img src="https://user-images.githubusercontent.com/14121125/188486750-5467e9e3-bcab-4037-ba90-a91c914a3000.jpg" alt="drawing" width="190"/>
      <img src="https://user-images.githubusercontent.com/14121125/188486868-b581655e-6cd5-42a9-8d29-df5246bd3387.jpg" alt="drawing" width="190"/>
      <img src="https://user-images.githubusercontent.com/14121125/188487963-31297d1c-f30e-463a-8ee7-6669ef77e313.jpg" alt="drawing" width="190"/>
     <img src="https://user-images.githubusercontent.com/14121125/188486939-ea1d4af6-885a-44fd-aedd-e6194d0ac25d.jpg" alt="drawing" width="190"/>
    </div>
</body>

**Comment by karlca** [comment]
Unfortunately, it didn't work!

**Comment by karlca** [comment]
![image](https://user-images.githubusercontent.com/37470902/188665201-630040ee-a280-4ad6-a152-77ab82116963.png)
I think it might be the problem here in  MauiProgram.cs

**Comment by danielmonettelli** [comment]
@karlca you are absolutely right, I think that is the problem, I attach the documentation so you can generate your **Dsn** in Sentry, and I will also add the respective steps to the README. Thank you very much for the help provided.

https://docs.sentry.io/platforms/dotnet/guides/maui/
