### ISSUE TITLE
crash on launch mac catalyst

### ISSUE THREAD

**Issue by rlalance** [danielmonettelli/netmaui-mitawi-app-challenge#11]
Steps to reproduce:
- Clone 
- Navigate to folder `netmaui-mitawi-app-challenge/Mitawi`
- On CLI, run: `dotnet build -t:Run -f net6.0-maccatalyst`
- Crashes on launch.
![Screen Shot 2022-09-14 at 2 28 15 PM](https://user-images.githubusercontent.com/1323032/190233789-3049a589-e0c7-45ad-8e83-878912726855.png)

Mac: Monterey 12.6

**Comment by danielmonettelli** [comment]
Hi @rlance, I have implemented the respective location permissions. Don't forget to also add the Sentry DSN and generate the OpenWeather API key, the steps are in the README.
