### ISSUE TITLE
Crash on launch android pixel 4a

### ISSUE THREAD

**Issue by rlalance** [danielmonettelli/netmaui-mitawi-app-challenge#12]
Steps to reproduce:
- Clone repo
- Navigate to: `netmaui-mitawi-app-challenge/Mitawi`
- On CLI, run: `dotnet build -t:Run -f net6.0-android`

**Comment by danielmonettelli** [comment]
Hi @rlance, I have implemented the respective location permissions. Don't forget to also add the Sentry DSN and generate the OpenWeather API key, the steps are in the README.
