### ISSUE TITLE
Error Maui.Skeleton

### ISSUE THREAD

**Issue by Octopon** [danielmonettelli/netmaui-mitawi-app-challenge#15]
Hi. I can't build the project. Please tell me how can I fix this problem? 
Thanks
![image](https://user-images.githubusercontent.com/16943861/220324275-9de65ccc-aa19-428f-ba6c-f6445210dd79.png)
![image](https://user-images.githubusercontent.com/16943861/220325068-aa6ff936-5520-4408-9a64-40321956426e.png)

**Comment by artem-reush** [comment]
I faced the same problem. Did you manage to find a solution?

> Hi. I can't build the project. Please tell me how can I fix this problem? Thanks ![image](https://user-images.githubusercontent.com/16943861/220324275-9de65ccc-aa19-428f-ba6c-f6445210dd79.png) ![image](https://user-images.githubusercontent.com/16943861/220325068-aa6ff936-5520-4408-9a64-40321956426e.png)

**Comment by danielmonettelli** [comment]
Hello @Octopon @artem-reush, I am very grateful for your reports. If I may, I'd like to suggest you to add the Maui.Skeleton package, you must install it via the command line. The following link will take you directly to the necessary information. If you have any questions or need additional help feel free to ask, I'll be more than happy to help.

https://github.com/users/danielmonettelli/packages/nuget/package/Maui.Skeleton

![Captura de pantalla (266)](https://user-images.githubusercontent.com/14121125/213599942-f921c4cd-8e2b-40f7-a012-34672f5ca0ab.png)

**Comment by artem-reush** [comment]
Unfortunately this doesn't solve the problem...
When executing the command, the following errors occur:
1. Maui.Skeleton package could not be found. There are no packages with this ID in the following package sources: C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org
2. Package "Maui.Skeleton" is not compatible with "all" platforms in project "C:\Users\Reush\Desktop\netmaui-mitawi-app-challenge\Mitawi\Mitawi.csproj".

![image](https://user-images.githubusercontent.com/36593483/221943953-c8c7b986-1143-4de1-81bf-d3d0f0ac0e88.png)

**Comment by danielmonettelli** [comment]
One solution is to download the Maui.Skeleton NuGet package from my repository and create a local route. However, please note that this is temporary until the owner updates the NuGet package to .NET MAUI. I hope this solution is useful for you. If you have any other questions, don't hesitate to ask me.

- [Temporary repository for the Maui.Skeleton NuGet Package.](https://github.com/danielmonettelli/Maui.Skeleton)

![Captura de pantalla (289)](https://user-images.githubusercontent.com/14121125/221953222-30d112c9-c0a2-46ac-abe9-771bc39ee552.png)

**Comment by Octopon** [comment]
@danielmonettelli  Thank you very much, the build is successful. It has not yet been possible to fully launch the application, since you need to register in the services. What was the problem, what did you fix in the package?
![image](https://user-images.githubusercontent.com/16943861/221962119-1da06b38-5731-4166-83f5-b8bb68b18c4b.png)

**Comment by Octopon** [comment]
@danielmonettelli Please tell me about the Sentry service. If I understood correctly from the description of the free plan, then the limit is 50 thousand errors. What happens if I exceed this limit? Due to the excess of the free limit, will the service inside my application throw an exception and for which my application may fall? 

Perhaps you know the answers. Regardless of the answers, thank you very much

**Comment by danielmonettelli** [comment]
Greetings, I would like to point out that the Maui.Skeleton NuGet package temporarily shares the same features as Xamarin.Forms.Skeleton, until an official version is released by the owner. Also, I suggest you dig into more detail about the Sentry.Maui package to get a fuller understanding of the topic. If you have any other questions, feel free to let me know.

- [.NET MAUI Error & Performance Monitoring.](https://sentry.io/for/dotnet-maui/)

**Comment by danielmonettelli** [comment]
Greetings! I wanted to let you know that the owner of the NuGet Package HorusStudio.Maui.Skeleton has recently updated it, so the Mitawi project has made the necessary changes to fix the issue they reported. It should now work correctly. Thank you!

- https://github.com/HorusSoftwareUY/Xamarin.Forms.Skeleton#setup

**Comment by danielmonettelli** [comment]
Before closing this issue, I would like to express my most sincere gratitude to @Octopon and @artem-reush for their valuable help in solving the problem and for the time dedicated to it. If you have any other questions or problems in the future, feel free to submit, I'll be happy to help you in any way I can. Thanks again for everything!
