### ISSUE TITLE
Crashing while deploying to Android Emulator

### ISSUE THREAD

**Issue by sattasundar** [danielmonettelli/netmaui-mitawi-app-challenge#9]
I have cloned and trying to run in android emulator after required config, but it's crashing on launch;

`System.NullReferenceException: 'The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class.'`

**Comment by danielmonettelli** [comment]
Hi @sattasundar, thank you very much for reporting your issue, the same thing happened to me, it seems to be a .NET MAUI bug. My temporary solution is to manually enable app location permissions.

**Comment by danielmonettelli** [comment]
Hi @sattasundar, I have implemented the respective location permissions. Don't forget to also add the Sentry DSN and generate the OpenWeather API key, the steps are in the README.
